# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrike < Formula
  desc "Hunt runaway, zombie, and herd processes on your Mac"
  homepage "https://github.com/d56de/shrike"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/d56de/shrike/releases/download/v0.1.0/shrike_0.1.0_darwin_amd64.tar.gz"
    sha256 "f9fb18431e5dd1c5d1f92e20b77123a4b6a8a76b5284e76493eea1a61cd4f5f6"

    define_method(:install) do
      bin.install "shrike"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/d56de/shrike/releases/download/v0.1.0/shrike_0.1.0_darwin_arm64.tar.gz"
    sha256 "2b8d916fa3e7a5ef1391c16dfb56add712c8cc0e9b4a99b6103974406a73d3ae"

    define_method(:install) do
      bin.install "shrike"
    end
  end

  test do
    system "#{bin}/shrike", "version"
  end
end
