# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrike < Formula
  desc "Hunt runaway, zombie, and herd processes on your Mac"
  homepage "https://github.com/d56de/shrike"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/d56de/shrike/releases/download/v0.5.0/shrike_0.5.0_darwin_amd64.tar.gz"
    sha256 "8b2209e49dd50ddeb50656a71069d04153f567511e4c633cfbaa1f2b8c38df7a"

    define_method(:install) do
      bin.install "shrike"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/d56de/shrike/releases/download/v0.5.0/shrike_0.5.0_darwin_arm64.tar.gz"
    sha256 "d0971c065c31babca8bdf09c147f70ba1d5de4bc10927f49c0d1a50fe3aa19d0"

    define_method(:install) do
      bin.install "shrike"
    end
  end

  test do
    system "#{bin}/shrike", "version"
  end
end
